spring:
  application:
    name: app
  servlet:
    multipart:
      max-file-size: 1MB
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
  mail:
    host: localhost
    port: 1025
    username: bartek
    password: bartek
    properties:
      mail:
        smtp:
          trust: "*"
          starttls:
            enable: false
            required: false
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://localhost:5433/book-share-db?schema=book_share
    username: bartek
    password: bartek
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  threads:
    virtual:
      enabled: true

mail:
  from: "bookshare@gmail.com"
  activationUrl: http://localhost:4200/activate-account

security:
  frontend:
    url: http://localhost:4200/
  activationCodeExpireTime: 120
  jwt:
    secretKey: zFwPKYRM4OFeVtMRHoLPbSxi6zbyj5rwMHCPzEELh3I=
    expiration: 86400000
logging:
  level:
    liquibase: DEBUG
    liquibase.changelog: DEBUG