spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:3306/springjdbc
    username: guest_user
    password: guest_password
    driver-class-name: org.postgresql.Driver